// Generated by scripts/build-brand-assets.mjs. Do not edit by hand.
//
// The site paints these at a fixed height with w-auto, so the numbers below
// are each lockup scaled to a common declared height: what next/image reads
// off them is the aspect ratio and a sane srcset width, not the final size.

export type BrandLockup = { src: string; width: number; height: number };

export const BRAND_LOCKUP: Record<"day" | "night", BrandLockup> = {
  day: { src: "/brand/logo-horizontal.png", width: 245, height: 60 },
  night: { src: "/brand/logo-night-horizontal.png", width: 271, height: 60 },
};
